version: '2'
services:
  ubuntu:
    image: ubuntu:latest
    environment:
      - GITHUB_LOGIN=${GITHUB_LOGIN}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO=${GITHUB_REPO}
      - GITHUB_ACCOUNT=${GITHUB_ACCOUNT}
