version: '2'
services:
  ubuntu:
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
    environment:
      - GITHUB_LOGIN=${GITHUB_LOGIN}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO=${GITHUB_REPO}
      - GITHUB_ACCOUNT=${GITHUB_ACCOUNT}
